export { Home } from "./home"
export { Ilustration } from "./ilustration"
export { Parnerships } from "./parnerships"
export { PastExperiences } from "./pastExperiences"
export { TokenizenConquer } from "./tokenizenConquer"
export { WhyUplify } from "./whyUplify"
export { FutureEntretainment } from "./futureEntretainment"